### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by triski** [hzeroo/twitch-desktop#1]
Guys,

Loving the app - its actually the best app to use.
I have 1 kind request if possible.
Better twitch TV makes chat a little better a number of ways,
when you @ someone it brings up a list of users to choose from.
And when they message you, it shows up with a colour fill.

Could you review and see if possible??

Thx in adv, as above I think the app is great :)

**Comment by hryuk** [comment]
Working on it :) .

**Comment by hryuk** [comment]
Implemented in cbc5bab04ddd927eb56b49d3183bd58daf8d0006. Will be included in next version.
