### ISSUE TITLE
Support TOTP

### ISSUE THREAD

**Issue by Generator** [hzeroo/twitch-desktop#14]
Account with two step verification are unable to login.

**Comment by x0rld** [comment]
do you have an error like this ?
![image](https://user-images.githubusercontent.com/45242856/71373261-db323e00-25b6-11ea-86e0-d5d5f97b3786.png)

**Comment by hryuk** [comment]
> do you have an error like this ?
> ![image](https://user-images.githubusercontent.com/45242856/71373261-db323e00-25b6-11ea-86e0-d5d5f97b3786.png)

Yes, started happening some days ago. Will try fix it this week.

**Comment by hryuk** [comment]
Fixed in 2.6.0
