### ISSUE TITLE
loading loop

### ISSUE THREAD

**Issue by estUser1** [hzeroo/twitch-desktop#18]
App is in a loading loop while nothing being displayed. 

Win10 
Version: 2.5.0

**Comment by hryuk** [comment]
Fixed in 2.6.0

**Comment by estUser1** [comment]
Thanks, but it still doesn't work for me with version 2.6.0

**Comment by hryuk** [comment]
I couldn't reproduce it locally. Can you try deleting `%APPDATA%/twitch-desktop`. I know the update process was a bit messy on windows, maybe some update didn't finished properly and is blocking the application initialization.

**Comment by estUser1** [comment]
Thanks for the reply. Deleting "%APPDATA%/twitch-desktop" fixed the issue :)

If I may, I have three improvements you probably have planned anyway.

1. ffz support (chat doesn't load when enabling BetterTTV btw)
2. smaller and more tiles for streams/categories when increasing window size
3. minimize streaming window when looking for other streams/favorites

**Comment by hryuk** [comment]
Thank you for feedback, very appreciated. Will be reviewing that during the coming days :) .
