### ISSUE TITLE
discord or skype

### ISSUE THREAD

**Issue by EnigmaCenter** [hzeroo/twitch-desktop#2]
Do you have any of this I would like to talk to you

**Comment by luistangui** [comment]
@EnigmaCenter  He doesn't have any of this, but I can try to contact him if you need something in the app or there is a defect.

**Comment by hzeroo** [comment]
Hi there!

You can contact me on discord: Hryuk#1591

Sadly I have no mic during summer at least, maybe I can find one but we can chat anyways.

See you
