### ISSUE TITLE
Error message: Failed fetching games

### ISSUE THREAD

**Issue by Krappa420** [hzeroo/twitch-desktop#27]
It was working fine yesterday, this morning getting error message when you open the app, failed fetching games. None of the left side icons work, channels, favorites, streamers, they are all on a loading circle loop. Please fix and update! This is the best desktop app! If you can also make the BTTV emotes work that would be great.

**Comment by hryuk** [comment]
Thanks for reporting! Working on a fix right now, seems linke twitch changed the graphql schema.

**Comment by Krappa420** [comment]
Thank you, When do you plan to release the update?

**Comment by hryuk** [comment]
v2.7.0 has just been released :)
