### ISSUE TITLE
New chat error/broken

### ISSUE THREAD

**Issue by Krappa420** [hzeroo/twitch-desktop#30]
Please look at the screenshot below of the chat

![image](https://user-images.githubusercontent.com/66475753/84333169-cc7b1b80-ab43-11ea-88e2-694c99f2a58d.png)

**Comment by Vixtron** [comment]
Same issue

**Comment by hryuk** [comment]
Working on it :)

**Comment by Krappa420** [comment]
> Working on it :)

I am so glad you are back. I am glad you are safe as well. I was worried.
