### ISSUE TITLE
`npm install` using excessive amounts of memory

### ISSUE THREAD

**Issue by Krutonium** [hzeroo/twitch-desktop#4]
I tried to build this as per the readme, and it consumed all of my system memory opening hundreds of npm and node processes, using excessive amounts of memory. My Desktop with 8GB of RAM is completely locked up, and a friend who has 16GB of memory has it running right up against that limit. Neither of us were able to let it finish, running out of memory.

**Comment by rwjuk** [comment]
This happens on Linux and Windows - put me down as a third report of this behaviour. It seems that only one of the `npm` processes is actually doing anything (i.e I/O operations) at any given time.

**Comment by marijnvdwerf** [comment]
Fyi, the issue appears to occur in the post-install step:
```txt
...
gyp info ok 
Installed to /Users/Marijn/temp/twitch-desktop/node_modules/node-sass/vendor/darwin-x64-57/binding.node

> twitch-desktop@1.0.0 postinstall /Users/Marijn/temp/twitch-desktop
> install-app-deps

Installing app dependencies for arch x64 to /Users/Marijn/temp/twitch-desktop

^C⏎  
```

**Comment by hryuk** [comment]
Can you guys post the node and npm versions that is causing the issue?

`node --version`
`npm --version`

**Comment by marijnvdwerf** [comment]
```
$ node --version
v8.9.0

$ npm --version
5.5.1
```

**Comment by Krutonium** [comment]
```
node --version

9.2.0

npm --version

5.5.1

```

**Comment by Bug38** [comment]
Having the same issue, with :
- npm -v  5.7.1
- node -v 6.13.0

So I tried to manually install all deps, then to run npm install again.

I got :
`
➜  twitch-desktop git:(master) ✗ npm install

> twitch-desktop@1.0.0 postinstall /home/lgmd/development/twitch-desktop
> install-app-deps

Installing app dependencies for arch x64 to /home/lgmd/development/twitch-desktop

> twitch-desktop@1.0.0 postinstall /home/lgmd/development/twitch-desktop
> install-app-deps

Installing app dependencies for arch x64 to /home/lgmd/development/twitch-desktop

> twitch-desktop@1.0.0 postinstall /home/lgmd/development/twitch-desktop
> install-app-deps

Installing app dependencies for arch x64 to /home/lgmd/development/twitch-desktop

> twitch-desktop@1.0.0 postinstall /home/lgmd/development/twitch-desktop
> install-app-deps

Installing app dependencies for arch x64 to /home/lgmd/development/twitch-desktop

> twitch-desktop@1.0.0 postinstall /home/lgmd/development/twitch-desktop
> install-app-deps

Installing app dependencies for arch x64 to /home/lgmd/development/twitch-desktop

> twitch-desktop@1.0.0 postinstall /home/lgmd/development/twitch-desktop
> install-app-deps

Installing app dependencies for arch x64 to /home/lgmd/development/twitch-desktop

> twitch-desktop@1.0.0 postinstall /home/lgmd/development/twitch-desktop
> install-app-deps

Installing app dependencies for arch x64 to /home/lgmd/development/twitch-desktop

> twitch-desktop@1.0.0 postinstall /home/lgmd/development/twitch-desktop
> install-app-deps

Installing app dependencies for arch x64 to /home/lgmd/development/twitch-desktop
^C.................] \ loadIdealTree:loadAllDepsIntoIdealTree: sill install loadIdealTree
`

**Comment by victorz** [comment]
Same here.

Had to kill the build when it was taking 10+ GB of memory, so as not to sink my machine. Also at the same place as the rest: `Installing app dependencies for arch x64 to [...]/twitch-desktop`

```
% node --version
v11.13.0
% npm --version
6.9.0
```

**Comment by hryuk** [comment]
Try with the new branch Angular7. Still a some things not working, but i'm on it. 

`git checkout Angular7`
`npm i`
`npm start`

**Comment by hryuk** [comment]
This should be fixed on the new version just released. It's suggested now to use yarn instead of npm, but npm should work too without issues.

4062e15
